### ISSUE TITLE
box-shadowのカラーをその場所で変えれるようにすべきかどうか

### ISSUE THREAD

**Issue by ddryo** [lism-ui/lism-ui#4]
box-shadowのカラーをその場所で変えれるようにすると便利だし面白いかなと思うが、一気に複雑になる。
（シャドウを2重にしてより立体感を出したりしているため、よりこの問題が大きい。）

```css
:root {
  --shadow--1: var(--sh-size--0) var(--sh-color), var(--sh-size--1) var(--sh-color);
  ...
}
```

のようにルートで変数をセットすると、その時点のカラーで固定されてしまうため、シャドウをつける要素に対して`--sh-color`を指定してカラーの上書きはできない。

なので次のようにしてユーティリティクラス側で初めてシャドウのセットをしなくてはいけない。

```css
.-bxsh\:1 {
  box-shadow: var(--sh-size--0) var(--sh-color), var(--sh-size--1) var(--sh-color);
}
...
```

こうすることで、次のようにしてシャドウカラーをその要素でだけ変更できる。

```html
<div class="-bxsh:1" style="--sh-color:rgba(250,250,250,0.2)">
```

が、実際これをできるようにしてみると処理はかなり複雑になり、ユーザー側が注意すべき点が増えてしまった。hover時のことも考えるとかなり複雑になる。

特に大きなデメリットとして、ユーティリティクラスの活用時以外で`var(--shadow--1) `のような変数での手軽な利用もできない点が挙げられる。
